name: Resolve CICD context
description: Resolve CICD helper script location and optionally checkout the helper repo.
inputs:
  cicd_repo:
    description: Repository containing CICD helper scripts (owner/repo).
    required: false
    default: ""
  cicd_ref:
    description: Ref (branch or tag) for CICD helper scripts.
    required: false
    default: ""
outputs:
  cicd_repo:
    description: Resolved CICD helper repository.
    value: ${{ steps.resolve.outputs.cicd_repo }}
  cicd_ref:
    description: Resolved CICD helper ref.
    value: ${{ steps.resolve.outputs.cicd_ref }}
  cicd_repo_dir:
    description: Path to CICD repo directory on disk.
    value: ${{ steps.resolve.outputs.cicd_repo_dir }}
  cicd_scripts_dir:
    description: Path to CICD helper scripts.
    value: ${{ steps.resolve.outputs.cicd_scripts_dir }}
  cicd_need_checkout:
    description: Whether the helper repo should be checked out.
    value: ${{ steps.resolve.outputs.cicd_need_checkout }}
runs:
  using: composite
  steps:
    - id: resolve
      shell: bash
      env:
        WORKFLOW_REF: ${{ github.workflow_ref }}
        ACTION_REPO: ${{ github.action_repository }}
        ACTION_REF: ${{ github.action_ref }}
        ACTION_PATH: ${{ github.action_path }}
        INPUT_CICD_REPO: ${{ inputs.cicd_repo }}
        INPUT_CICD_REF: ${{ inputs.cicd_ref }}
      run: |
        python3 "$ACTION_PATH/resolve.py"
    - name: Checkout CICD scripts
      uses: actions/checkout@v4
      if: steps.resolve.outputs.cicd_need_checkout == 'true'
      with:
        repository: ${{ steps.resolve.outputs.cicd_repo }}
        ref: ${{ steps.resolve.outputs.cicd_ref }}
        token: ${{ secrets.GITHUB_TOKEN || secrets.GH_TOKEN || github.token }}
        path: .cicd
        fetch-depth: 1
    - name: Ignore CICD helper checkout
      if: steps.resolve.outputs.cicd_need_checkout == 'true'
      shell: bash
      run: |
        exclude_file="${GITHUB_WORKSPACE}/.git/info/exclude"
        if [ -f "${exclude_file}" ] && ! grep -qx "/.cicd/" "${exclude_file}"; then
          echo "/.cicd/" >> "${exclude_file}"
        fi
