name: Resolve CICD helper repo
description: Resolve CICD helper scripts location and export CICD_* env vars.
inputs:
  cicd_ref:
    description: Ref (branch or tag) for CICD helper scripts.
    required: false
    default: "mainline"
outputs:
  cicd_repo:
    description: Resolved CICD helper repository.
    value: ${{ steps.resolve.outputs.cicd_repo }}
  cicd_ref:
    description: Resolved CICD helper ref.
    value: ${{ steps.resolve.outputs.cicd_ref }}
  cicd_repo_dir:
    description: Path to CICD repo directory on disk.
    value: ${{ steps.resolve.outputs.cicd_repo_dir }}
  cicd_scripts_dir:
    description: Path to CICD helper scripts.
    value: ${{ steps.resolve.outputs.cicd_scripts_dir }}
  cicd_need_checkout:
    description: Whether the helper repo should be checked out.
    value: ${{ steps.resolve.outputs.cicd_need_checkout }}
runs:
  using: composite
  steps:
    - id: resolve
      shell: bash
      env:
        INPUT_CICD_REF: ${{ inputs.cicd_ref }}
      run: |
        repo="snw35/cicd"
        ref="${INPUT_CICD_REF:-}"
        if [ -z "$ref" ]; then
          if [ "$GITHUB_REPOSITORY" = "$repo" ] && [ -n "${GITHUB_REF_NAME:-}" ]; then
            ref="${GITHUB_REF_NAME}"
          else
            ref="mainline"
          fi
        fi
        if [ "$repo" = "$GITHUB_REPOSITORY" ] && [ -d "${GITHUB_WORKSPACE}/.github/scripts" ]; then
          repo_dir="${GITHUB_WORKSPACE}"
          scripts_dir="${repo_dir}/.github/scripts"
          need_checkout="false"
        else
          repo_dir="${GITHUB_WORKSPACE}/.cicd"
          scripts_dir="${repo_dir}/.github/scripts"
          need_checkout="true"
        fi
        {
          echo "CICD_REPO=$repo"
          echo "CICD_REF=$ref"
          echo "CICD_REPO_DIR=$repo_dir"
          echo "CICD_SCRIPTS_DIR=$scripts_dir"
          echo "CICD_NEED_CHECKOUT=$need_checkout"
        } >> "$GITHUB_ENV"
        {
          echo "cicd_repo=$repo"
          echo "cicd_ref=$ref"
          echo "cicd_repo_dir=$repo_dir"
          echo "cicd_scripts_dir=$scripts_dir"
          echo "cicd_need_checkout=$need_checkout"
        } >> "$GITHUB_OUTPUT"
